version: '3.1'
services:

  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - 27017:27017

  api:
    build: ./api
    container_name: fastapi
    ports:
      - 60001:8000

  airflow:
    build: ./docker/airflow
    image: pluralsight/airflow
    restart: always
    container_name: airflow
    environment:
      - AIRFLOW__CORE__FERNET_KEY="Z27wHAQxCObGWbIYyp06PlNoNlV7hyLO5zT74itoQww="
      - AIRFLOW__API__AUTH_BACKEND=airflow.api.auth.backend.default
    volumes:
      - ./dags19:/usr/local/airflow/dags
      - ./docker/airflow/fileinput:/fileinput
    ports:
      - 8081:8080
    healthcheck:
      test: [ "CMD", "nc", "-z", "airflow", "8080" ]
      timeout: 45s
      interval: 10s
      retries: 10


networks:
  default:
    name: airflow-network