version: '2.1'
services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672


  airflow:
    build: ./docker/airflow
    image: pluralsight/airflow
    restart: always
    container_name: airflow
    environment:
      - AIRFLOW__CORE__FERNET_KEY="Z27wHAQxCObGWbIYyp06PlNoNlV7hyLO5zT74itoQww="
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./docker/airflow/fileinput:/fileinput
    ports:
      - 8080:8080
    healthcheck:
      test: [ "CMD", "nc", "-z", "airflow", "8080" ]
      timeout: 45s
      interval: 10s
      retries: 10


networks:
  default:
    name: airflow-network